# Generated by Django 4.1.13 on 2024-06-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_user',
            name='devices',
        ),
        migrations.AddField(
            model_name='admin_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_At'),
        ),
    ]
