# Generated by Django 4.1.13 on 2024-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_category_subcategory_category_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_At'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
