# Generated by Django 4.1.13 on 2024-06-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_remove_admin_user_devices_admin_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_user',
            name='created_at',
        ),
        migrations.AddField(
            model_name='admin_user',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
