# Generated by Django 4.1.13 on 2024-06-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_remove_admin_user_created_at_admin_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_device',
            name='device_name',
            field=models.CharField(max_length=100, verbose_name='device_name'),
        ),
    ]
