# Generated by Django 4.1.13 on 2024-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_admin_device_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_At'),
        ),
        migrations.AddField(
            model_name='admin_user',
            name='devices',
            field=models.ManyToManyField(related_name='user_devices', to='admin.admin_device'),
        ),
    ]
