# Generated by Django 4.1.13 on 2024-06-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_admin_user_created_at_admin_user_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_device',
            name='user',
        ),
        migrations.AlterField(
            model_name='admin_user',
            name='devices',
            field=models.ManyToManyField(to='admin.admin_device'),
        ),
    ]
