# Generated by Django 4.1.13 on 2024-06-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_remove_admin_device_user_alter_admin_user_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_devices', to='admin.admin_user'),
        ),
    ]
