# Generated by Django 4.1.13 on 2024-06-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('random_access_point', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('profile_image', models.CharField(blank=True, max_length=225, null=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=200)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_order', models.PositiveIntegerField(default=0)),
                ('completed_order', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('gig_limit', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('is_number_verified', models.BooleanField(default=False)),
                ('devices', models.ManyToManyField(related_name='user_devices', to='seller.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_devices', to='seller.user'),
        ),
    ]
