# Generated by Django 4.1.13 on 2024-05-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(blank=True, default='', max_length=225, null=True),
        ),
    ]
