# Generated by Django 4.1.13 on 2024-06-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('translated_label', models.CharField(max_length=100)),
                ('edit_type', models.CharField(max_length=100)),
                ('data_options', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Gig_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=100)),
                ('sub_category_id', models.CharField(max_length=100)),
                ('service_type', models.BooleanField()),
                ('server_type_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GigData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='common.gig_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.user')),
            ],
        ),
        migrations.CreateModel(
            name='GigMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'GigMetaData',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('has_nested_gig_metadata', models.BooleanField()),
                ('service_type', models.BooleanField()),
                ('is_price', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_subcategories', to='common.category')),
            ],
            options={
                'db_table': 'Subcategory',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('has_nested_gig_metadata', models.BooleanField()),
                ('has_gig_price', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='common.subcategory')),
            ],
            options={
                'db_table': 'ServiceType',
            },
        ),
        migrations.CreateModel(
            name='Select_User_Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_unit', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('is_duration_limit', models.BooleanField()),
                ('is_content', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='common.gigdata')),
            ],
            options={
                'db_table': 'UserPackages',
            },
        ),
        migrations.CreateModel(
            name='Select_content_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('translated_label', models.CharField(max_length=100)),
                ('edit_type', models.CharField(max_length=100)),
                ('included_modifications', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('selected_user_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='common.select_user_packages')),
            ],
            options={
                'db_table': 'UserPackages_Content',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_unit', models.CharField(max_length=100)),
                ('is_duration_limit', models.BooleanField()),
                ('is_content', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('servicetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='common.servicetype')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='common.subcategory')),
            ],
            options={
                'db_table': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gig_meta_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_options', to='common.gigmetadata')),
            ],
            options={
                'db_table': 'Options',
            },
        ),
        migrations.AddField(
            model_name='gigmetadata',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='common.servicetype'),
        ),
        migrations.AddField(
            model_name='gigmetadata',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='common.subcategory'),
        ),
        migrations.AddField(
            model_name='gig_category',
            name='gig',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='common.gigdata'),
        ),
        migrations.CreateModel(
            name='DurationLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key_of_packages', to='common.packages')),
            ],
            options={
                'db_table': 'duration_limit',
            },
        ),
        migrations.CreateModel(
            name='DataOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('val', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key_of_packages', to='common.content')),
            ],
            options={
                'db_table': 'data_options',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_key_of_content', to='common.packages'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(related_name='categories', to='common.subcategory'),
        ),
    ]
