# Generated by Django 4.1.13 on 2024-06-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigmetadata',
            name='options',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='duration_limit',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='title',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='service_type_data',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Select_User_Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_unit', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('is_duration_limit', models.BooleanField()),
                ('is_content', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='common.gigdata')),
            ],
            options={
                'db_table': 'UserPackages',
            },
        ),
        migrations.CreateModel(
            name='Select_content_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('translated_label', models.CharField(max_length=100)),
                ('edit_type', models.CharField(max_length=100)),
                ('included_modifications', models.IntegerField()),
                ('active', models.BooleanField()),
                ('selected_user_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='common.select_user_packages')),
            ],
            options={
                'db_table': 'UserPackages_Content',
            },
        ),
    ]
