# Generated by Django 4.1.13 on 2024-06-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigdata',
            name='click',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gigdata',
            name='impression',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100)),
                ('deliver_time', models.DateField()),
                ('order_status', models.CharField(max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer_user')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.gigdata')),
            ],
        ),
        migrations.CreateModel(
            name='Gig_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_url', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='common.gigdata')),
            ],
            options={
                'db_table': 'Gig_images',
            },
        ),
    ]
