# Generated by Django 4.1.13 on 2024-06-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigdata',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
