# Generated by Django 4.1.13 on 2024-06-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigmetadata',
            name='has_nested_gig_metadata',
        ),
    ]
