# Generated by Django 4.1.13 on 2024-06-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_packages_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='service_type_data',
        ),
    ]
