# Generated by Django 4.1.13 on 2024-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_gig_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigdata',
            name='click',
            field=models.IntegerField(default=0),
        ),
    ]
