# Generated by Django 4.1.13 on 2024-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_subcategory_service_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
