# Generated by Django 4.1.13 on 2024-06-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_gigdata_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigdata',
            name='impression',
            field=models.IntegerField(default=0),
        ),
    ]
