# Generated by Django 4.1.13 on 2024-06-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_subcategory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigmetadata',
            name='options',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='duration_limit',
        ),
    ]
