# Generated by Django 4.1.13 on 2024-06-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_gigmetadata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_categories',
        ),
    ]
